=== pochemuto/alv-ch-batches/master/company/src/main/resources/avgbetriebe.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2007 (http://www.altova.com) by Marcel Kessler (seco) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:complexType name="avggstelle">
		<xs:sequence>
			<xs:element name="Id">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Strasse" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PLZ" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Ort" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Telefonnummer" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="20"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Email" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="avgleiter">
		<xs:sequence>
			<xs:element name="Name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Vorname">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="avg">
		<xs:annotation>
			<xs:documentation>avg betriebe</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Betrieb" type="avgbetrieb" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="avgbetrieb">
		<xs:sequence>
			<xs:element name="Id">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="12"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Bezeichnung">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="150"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Strasse" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="100"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="PLZ">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="4"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Ort">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Telefonnummer" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="20"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Email" minOccurs="0">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:maxLength value="50"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="GStelle" type="avggstelle" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="Leiter" type="avgleiter" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== pochemuto/alv-ch-batches/master/company/src/test/resources/AVAMPSTS-3.xml
<?xml version="1.0" encoding="UTF-8"?>
<avg xsi:noNamespaceSchemaLocation="avgbetriebe.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
 <Betrieb>
  <Id>6</Id>
  <Bezeichnung>AF Personal AG is back!</Bezeichnung>
  <Strasse>Zürcherstrasse 29</Strasse>
  <PLZ>5620</PLZ>
  <Ort>Bremgarten</Ort>
  <Telefonnummer>0666666666</Telefonnummer>
  <Email>info@afpersonal.ch</Email>
  <Leiter>
   <Name>Furrer</Name>
   <Vorname>Anton</Vorname>
  </Leiter>
  <Leiter>
   <Name>Furrer</Name>
   <Vorname>Pamela</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>8</Id>
  <Telefonnummer>0627775308</Telefonnummer>
  <Bezeichnung>ASP Marketing AG</Bezeichnung>
  <Strasse>Kesslergasse 22</Strasse>
  <PLZ>5707</PLZ>
  <Ort>Seengen</Ort>
  <Email>andreas.somogyi@aspmarketing.ch</Email>
  <Leiter>
   <Name>Dr.</Name>
   <Vorname>Somogyi Andreas</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>10</Id>
  <Bezeichnung>Adecco human resources AG</Bezeichnung>
  <Strasse>Bahnhofstrasse 10</Strasse>
  <PLZ>5001</PLZ>
  <Ort>Aarau 1 Fächer</Ort>
  <Telefonnummer>0628347040</Telefonnummer>
  <Email>aarau@adecco.ch</Email>
  <Leiter>
   <Name>Keller</Name>
   <Vorname>Thomas</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>11</Id>
  <Bezeichnung>Adecco human resources AG</Bezeichnung>
  <Strasse>Mellingerstrasse 6</Strasse>
  <PLZ>5400</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0562002040</Telefonnummer>
  <Email>baden@adecco.ch</Email>
  <Leiter>
   <Name>Seipelt</Name>
   <Vorname>Dominik</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>12</Id>
  <Bezeichnung>Adecco Human Resources AG</Bezeichnung>
  <Strasse>Zentralstrasse 21</Strasse>
  <PLZ>5610</PLZ>
  <Ort>Wohlen AG</Ort>
  <Telefonnummer>0566187080</Telefonnummer>
  <Email>wohlen@adecco.ch</Email>
  <Leiter>
   <Name>Cariati</Name>
   <Vorname>Stephan</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>13</Id>
  <Bezeichnung>Agroimpuls</Bezeichnung>
  <Strasse>Laurstrasse 10</Strasse>
  <PLZ>5200</PLZ>
  <Ort>Brugg AG</Ort>
  <Telefonnummer>0564625144</Telefonnummer>
  <Email>info@agroimpuls.ch</Email>
  <Leiter>
   <Name>Schatzmann</Name>
   <Vorname>Monika</Vorname>
  </Leiter>
  <Leiter>
   <Name>Flückiger</Name>
   <Vorname>Hans Peter</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>14</Id>
  <Bezeichnung>Alegro AG Personal für Bau, Handwerk &amp; Regie</Bezeichnung>
  <Strasse>Mellingerstrasse 1</Strasse>
  <PLZ>5402</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0562034050</Telefonnummer>
  <Email>alegro@alegro.ch</Email>
  <Leiter>
   <Name>Grüninger</Name>
   <Vorname>Roger</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>15</Id>
  <Bezeichnung>Almobau AG</Bezeichnung>
  <Strasse>Rathausgasse 12</Strasse>
  <PLZ>5402</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0562221233</Telefonnummer>
  <Email>baden@almobau.ch</Email>
  <Leiter>
   <Name>Notter</Name>
   <Vorname>Daniel</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>16</Id>
  <Bezeichnung>Amigo temporär &amp; fest AG</Bezeichnung>
  <Strasse>c/o Serves AG Gartenstrasse 28</Strasse>
  <PLZ>5400</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0442775656</Telefonnummer>
  <Email>paul.zubler@amigo.ch</Email>
  <Leiter>
   <Name>Zubler</Name>
   <Vorname>Paul</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>20</Id>
  <Bezeichnung>Aroba Weisskopf AG</Bezeichnung>
  <Strasse>Grieshaldenweg 29</Strasse>
  <PLZ>4314</PLZ>
  <Ort>Zeiningen</Ort>
  <Telefonnummer>0618261414</Telefonnummer>
  <Email>info@aroba.ch</Email>
  <Leiter>
   <Name>Facciorusso</Name>
   <Vorname>Matteo</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>22</Id>
  <Bezeichnung>Atlas Personal Kleindöttingen René Mohr</Bezeichnung>
  <Strasse>Hauptstrasse 5</Strasse>
  <PLZ>5314</PLZ>
  <Ort>Kleindöttingen</Ort>
  <Telefonnummer>0562458100</Telefonnummer>
  <Email>info@atlas-personal.ch</Email>
  <Leiter>
   <Name>Mohr</Name>
   <Vorname>René</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>25</Id>
  <Bezeichnung>Baldegger, Personal- und Unternehmensberatung</Bezeichnung>
  <Strasse>Schachen 24</Strasse>
  <PLZ>5000</PLZ>
  <Ort>Aarau</Ort>
  <Telefonnummer>0628246757</Telefonnummer>
  <Email>info@baldegger-beratung.ch</Email>
  <Leiter>
   <Name>Baldegger</Name>
   <Vorname>Rainer</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>32</Id>
  <Bezeichnung>Busslinger Ursula, Personal- und Stellenvermittlung</Bezeichnung>
  <Strasse>Haldenweg 1</Strasse>
  <PLZ>5616</PLZ>
  <Ort>Meisterschwanden</Ort>
  <Telefonnummer>0566672348</Telefonnummer>
  <Email>sekretariat@wegst-busslinger.ch</Email>
  <Leiter>
   <Name>Wegst-Busslinger</Name>
   <Vorname>Ursula</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>34</Id>
  <Bezeichnung>Search Experts Erich Bähler</Bezeichnung>
  <Strasse>Fahrweidstrasse 50</Strasse>
  <PLZ>5630</PLZ>
  <Ort>Muri AG</Ort>
  <Telefonnummer>0566648185</Telefonnummer>
  <Email>t.baehler@oprandi.ch</Email>
  <Leiter>
   <Name>Bähler</Name>
   <Vorname>Erich</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>36</Id>
  <Bezeichnung>City-Art Tiziana Zeller</Bezeichnung>
  <Strasse>Fluhmattstrasse 12</Strasse>
  <PLZ>5400</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0562222205</Telefonnummer>
  <Email>info@cityart.ch</Email>
  <Leiter>
   <Name>Zeller</Name>
   <Vorname>Tiziana</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>38</Id>
  <Bezeichnung>Ralph Conrad Consulting GmbH</Bezeichnung>
  <Strasse>Theaterplatz 4</Strasse>
  <PLZ>5400</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0562250638</Telefonnummer>
  <Email>info@ralphconrad.ch</Email>
  <Leiter>
   <Name>Conrad</Name>
   <Vorname>Ralph</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>43</Id>
  <Bezeichnung>DLS Dienstleistungen für Stellenvermittlung &amp; Personalmanagement AG</Bezeichnung>
  <Strasse>Untere Grabenstrasse 42</Strasse>
  <PLZ>4800</PLZ>
  <Ort>Zofingen</Ort>
  <Telefonnummer>0627452525</Telefonnummer>
  <Email>dhuegli@dls.ch</Email>
  <Leiter>
   <Name>Hügli</Name>
   <Vorname>David</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>45</Id>
  <Bezeichnung>Diener Ruedi HR-Consulting</Bezeichnung>
  <Strasse>Strüblismattweg 5</Strasse>
  <PLZ>5073</PLZ>
  <Ort>Gipf-Oberfrick</Ort>
  <Telefonnummer>0628716947</Telefonnummer>
  <Email>ruedi.diener@rd-consulting.ch</Email>
  <Leiter>
   <Name>Diener</Name>
   <Vorname>Rudolf</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>48</Id>
  <Bezeichnung>Drehpunkt Personal GmbH</Bezeichnung>
  <Strasse>Fliederweg 6</Strasse>
  <PLZ>5037</PLZ>
  <Ort>Muhen</Ort>
  <Telefonnummer>0627375585</Telefonnummer>
  <Email>info@drehpunktpersonal.ch</Email>
  <GStelle>
   <Id>20152</Id>
   <Strasse>Luzernerstrasse 21</Strasse>
  <PLZ>4665</PLZ>
  <Ort>Oftringen</Ort>
   <Telefonnummer>0627889820</Telefonnummer>
   <Email>info@drehpunktpersonal.ch</Email>
  </GStelle>
  <GStelle>
   <Id>27176</Id>
   <Strasse>Klosterstrasse 40</Strasse>
  <PLZ>5430</PLZ>
  <Ort>Wettingen</Ort>
   <Telefonnummer>0564378070</Telefonnummer>
   <Email></Email>
  </GStelle>
  <Leiter>
   <Name>Müller</Name>
   <Vorname>Lukas</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>52</Id>
  <Bezeichnung>JobTalente GmbH</Bezeichnung>
  <Strasse>Ammerswilerstrasse 21 d</Strasse>
  <PLZ>5600</PLZ>
  <Ort>Lenzburg</Ort>
  <Telefonnummer>0628882888</Telefonnummer>
  <Email>info@jobtalente.ch</Email>
  <Leiter>
   <Name>Eicher</Name>
   <Vorname>Rolf R.</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>55</Id>
  <Bezeichnung>Enemag Telecom AG</Bezeichnung>
  <Strasse>Mellingerstrasse 2</Strasse>
  <PLZ>5413</PLZ>
  <Ort>Birmenstorf AG</Ort>
  <Telefonnummer>0562973336</Telefonnummer>
  <Email>enemag@enemag.ch</Email>
  <Leiter>
   <Name>Järmann</Name>
   <Vorname>Werner</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>58</Id>
  <Bezeichnung>Excellent Personaldienstleistungen Baden AG</Bezeichnung>
  <Strasse>Langhaus 1 / beim Bahnhof</Strasse>
  <PLZ>5400</PLZ>
  <Ort>Baden</Ort>
  <Telefonnummer>0562002080</Telefonnummer>
  <Email>deck@excellent.ch</Email>
  <Leiter>
   <Name>Deck</Name>
   <Vorname>Mathias</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>59</Id>
  <Bezeichnung>Fey Sütterlin Erika</Bezeichnung>
  <Strasse>Sood 1</Strasse>
  <PLZ>5727</PLZ>
  <Ort>Oberkulm</Ort>
  <Telefonnummer>0627765069</Telefonnummer>
  <Email></Email>
  <Leiter>
   <Name>Fey Sütterlin</Name>
   <Vorname>Erika</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>60</Id>
  <Bezeichnung>GST Stellendienst AG Aarburg</Bezeichnung>
  <Strasse>Bahnhofstrasse 54</Strasse>
  <PLZ>4663</PLZ>
  <Ort>Aarburg</Ort>
  <Telefonnummer>0627874080</Telefonnummer>
  <Email>aarburg@gst-stellendienst.ch</Email>
  <Leiter>
   <Name>Cerasuolo</Name>
   <Vorname>Nunzio</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>63</Id>
  <Bezeichnung>Global Personal Partner AG</Bezeichnung>
  <Strasse>Albertstrasse 2</Strasse>
  <PLZ>5432</PLZ>
  <Ort>Neuenhof</Ort>
  <Telefonnummer>0564064344</Telefonnummer>
  <Email>neuenhof@global-personal.ch</Email>
  <Leiter>
   <Name>Scarabelli</Name>
   <Vorname>Luigi Ettore</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>68</Id>
  <Bezeichnung>Heureka-Gamma AG</Bezeichnung>
  <Strasse>Husmatt 1</Strasse>
  <PLZ>5405</PLZ>
  <Ort>Dättwil AG</Ort>
  <Telefonnummer>0564847060</Telefonnummer>
  <Email>info@heureka-gamma.ch</Email>
  <Leiter>
   <Name>Bader</Name>
   <Vorname>Dieter</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>70</Id>
  <Bezeichnung>ISM Group Personalservice-Montageunternehmung GmbH</Bezeichnung>
  <Strasse>Hauptstrasse 80</Strasse>
  <PLZ>4853</PLZ>
  <Ort>Murgenthal</Ort>
  <Telefonnummer>0629263550</Telefonnummer>
  <Email>ismgroup.murg@solnet.ch</Email>
  <Leiter>
   <Name>Gloor</Name>
   <Vorname>Thomas</Vorname>
  </Leiter>
 </Betrieb>
 <Betrieb>
  <Id>74</Id>
  <Bezeichnung>Job-House Sommerhalder &amp; Eichenberger</Bezeichnung>
  <Strasse>Burghaldenstrasse 59</Strasse>
  <PLZ>5600</PLZ>
  <Ort>Lenzburg 2</Ort>
  <Telefonnummer>0628863030</Telefonnummer>
  <Email>info@jobhouse.ch</Email>
  <Leiter>
   <Name>Eichenberger-Sommerhalder</Name>
